### ISSUE TITLE
Can you give a short guidance on how to use Control-LoRA canny with img2img and revision?

### ISSUE THREAD

**Issue by lanyusan** [MoonRide303/Fooocus-MRE#54] opened 2023-09-03 12:44 UTC
The UI is a little bit confusing.

For example do I need to tick image 2 image check box at the input tab when use canny for img2img?
Or just tick Control-Lora-Canny on the CN tab on the right side?
Or booth?

**Comment by hzeasy** [comment] 2023-09-03 14:35
Just as confused as you, an error will be reported as soon as the control is started, please guide！
![微信图片_20230903223227](https://github.com/MoonRide303/Fooocus-MRE/assets/136664755/abc99c89-91f3-4007-a8b9-67670a6cbf3a)

**Comment by barepixels** [comment] 2023-09-03 16:25
A few days ago I posted instructions for Canny here https://github.com/MoonRide303/Fooocus-MRE/discussions/39

**Comment by MoonRide303** [comment] 2023-09-03 19:00
@lanyusan Control-LoRAs can work in both txt2img and img2img modes, and will deliver different results, then.

If you want pixels from the original image to influence output image, then you use Image-2-Image mode. But if you don't do that, then Control-LoRAs can still guide generation and produce similar image to the input - Canny will use edge detection mechanism, and Depth will use depth information.

I am currently working on [wiki for MRE](https://github.com/MoonRide303/Fooocus-MRE/wiki), and adding samples illustrating how different parameters affect generation - I will add page for Control-LoRAs, too.

**Comment by MoonRide303** [comment] 2023-09-03 20:57
@lanyusan @barepixels I've added instructions with examples into [wiki / Control‐LoRAs](https://github.com/MoonRide303/Fooocus-MRE/wiki/Control%E2%80%90LoRAs) (for Canny and Depth). I used really crude input image, so it's easier to understand how those methods work in different modes :).

**Comment by MoonRide303** [comment] 2023-09-03 21:01
@hzeasy Please report your problem as separate issue, with some more details if possible. It looks like model file could be corrupted - maybe not fully downloaded?

**Comment by lanyusan** [comment] 2023-09-03 21:04
@MoonRide303 Thanks a lot.

**Comment by MoonRide303** [comment] 2023-09-04 16:45
I've also added [wiki page for Revision](https://github.com/MoonRide303/Fooocus-MRE/wiki/Revision) with some samples - closing.

**Closed by MoonRide303** 2023-09-04 16:45 UTC
Labels: documentation

**Comment by hzeasy** [comment] 2023-09-05 04:13
> @hzeasy请将您的问题作为单独的问题报告，并尽可能提供更多详细信息。看起来模型文件可能已损坏 - 可能未完全下载？
@MoonRide303 
When I re-downloaded the zip and upgraded, the problem was solved. The current version is 1.0.45. Can you explain the Image-2-Image tab in more detail? 
Thanks for creating them, really useful.

**Comment by hzeasy** [comment] 2023-09-05 04:16
> @hzeasy请将您的问题作为单独的问题报告，并尽可能提供更多详细信息。看起来模型文件可能已损坏 - 可能未完全下载？

@MoonRide303 When I re-downloaded the zip and upgraded, the problem was solved. The current version is 1.0.45. Can you explain the Image-2-Image tab in more detail? 
Thanks for creating them, really useful.感谢！

**Comment by MoonRide303** [comment] 2023-09-05 06:05
@hzeasy Basic description and samples for Image-2-Image mode are available on [Image-2-Image wiki page](https://github.com/MoonRide303/Fooocus-MRE/wiki/Image%E2%80%902%E2%80%90Image). Did you look into it? If so, and it's not enough - please say what kind of information would you like to see there.

**Comment by hzeasy** [comment] 2023-09-05 13:17
> @hzeasy[Image-2-Image 模式的基本描述和示例可在Image-2-Image wiki 页面](https://github.com/MoonRide303/Fooocus-MRE/wiki/Image%E2%80%902%E2%80%90Image)上找到。你调查过吗？如果是这样，这还不够 - 请说明您希望在那里看到什么类型的信息。

首先感谢您的回复，这段时间我一直在用您这个版本出图，真的很好。Image-2-Image 模式的基本描述认真看过了，利用INPUT进行生图没有疑问，但是Revision选项没有提及，希望了解Revision和INPUT这二项之间的关系，不清楚什么情况下使用LOAD Revision。谢谢，

也在这里再提个问题，就是LORA选项只有一个列表，好像是不能把LORA分类的，尝试了用目录分类好像没有效果。不分类真的有些乱。既然有LORA这个项目应该实现分类比较好！

**Comment by MoonRide303** [comment] 2023-09-05 14:20
@hzeasy Revision is described on a separate page, here: [wiki / Revision](https://github.com/MoonRide303/Fooocus-MRE/wiki/Revision).

I am planning to add support for more Control-LoRAs in future versions - you can subscribe to #53 to be notified when it's done.

**Comment by hzeasy** [comment] 2023-09-08 09:16
@MoonRide303 Hello, the error message I provided last time appeared again today, and now describe the error situation:
 1. Select "Load Image(s) to Revision" to select 4 images, and display them correctly in "Revision".
 2. Check the "Revision (prompting with images)" option,
For other options, use the default parameters after the startup window, click Start to run, and an error message will be reported in the background. 
After the error I aborted the process with crtl+C.
Attached are two screenshots.
![084fb3deca7d5ffe95d5c97911d8a21](https://github.com/MoonRide303/Fooocus-MRE/assets/136664755/159f395f-510a-48eb-9ed2-108cd9076513)
![3d7c81a34be2c08b1b176e86bf50960](https://github.com/MoonRide303/Fooocus-MRE/assets/136664755/5c67bc75-2221-4621-815b-0dc3596ebb70)

**Comment by MoonRide303** [comment] 2023-09-08 09:55
@hzeasy I tried to reproduce the problem on my PC (starting from clean v1.0.40, which updated on start) - it works just fine on my machine:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/8b30ff44-ed22-42c8-9ae3-ac9fb0f2c530)

But we can figuring it out. Some questions that might help here:
1. Did you make any changes in the code? (I can see you have different colors, for example)
2. Were there any errors earlier in the log, when MRE was starting?
3. Could you verify if the CLIP Vision model isn't corrupt? You can do it by checking it's SHA-256 hash, like that (in proper folder):
```
CertUtil -hashfile clip_vision_g.safetensors SHA256
SHA256 hash of clip_vision_g.safetensors:
9908329b3ead722a693ea400fab1d7c9ec91d6736fd194a94d20d793457f9c2e
CertUtil: -hashfile command completed successfully.
```
If it isn't damaged, then hash should be the same as above.

**Comment by hzeasy** [comment] 2023-09-08 11:55
@MoonRide303 Your judgment is correct, the problem lies in the CLIP file, its SHA-256 hash is wrong, it will be normal after re-downloading, perfect solution! That's really great, thank you for your patience and help.
I'd be happy to recommend this version to others and look forward to your updates.
![b7b715269885a5169c29dd3d4ee72e6](https://github.com/MoonRide303/Fooocus-MRE/assets/136664755/adcf2d26-149b-44eb-bc56-1142ff2f1696)
![6d726bf54b15ff2a8796f61b3dcabbf](https://github.com/MoonRide303/Fooocus-MRE/assets/136664755/9ace0fa8-bc32-4a51-af7c-aff72982daca)
