### ISSUE TITLE
RuntimeError: User specified autocast device_type must be 'cuda' or 'cpu'

### ISSUE THREAD

**Issue by jasoncow007** [MoonRide303/Fooocus-MRE#77] opened 2023-09-13 02:45 UTC
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus\Fooocus-MRE\modules\async_worker.py", line 373, in worker
    handler(task)
  File "D:\Fooocus\Fooocus-MRE\modules\async_worker.py", line 207, in handler
    t['c'][1] = pipeline.clip_encode(sd=pipeline.xl_refiner, texts=t['positive'],
  File "D:\Fooocus\Fooocus-MRE\modules\default_pipeline.py", line 224, in clip_encode
    cond, pooled = clip_encode_single(clip, text)
  File "D:\Fooocus\Fooocus-MRE\modules\default_pipeline.py", line 202, in clip_encode_single
    result = clip.encode_from_tokens(tokens, return_pooled=True)
  File "D:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 120, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "D:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\sdxl_clip.py", line 79, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "D:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd1_clip.py", line 18, in encode_token_weights
    out, pooled = self.encode(to_encode)
  File "D:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd1_clip.py", line 168, in encode
    return self(tokens)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus-MRE\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd1_clip.py", line 149, in forward
    with precision_scope(model_management.get_autocast_device(device), torch.float32):
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\amp\autocast_mode.py", line 201, in __init__
    raise RuntimeError('User specified autocast device_type must be \'cuda\' or \'cpu\'')
RuntimeError: User specified autocast device_type must be 'cuda' or 'cpu'

**Comment by ping3839** [comment] 2023-09-13 05:27
Having the same problem (it's when loading other Lora, if just loading “sd_xl_offset_example-lora_1.0.safetensors” no problem), when using “https://github.com/lllyasviel/Fooocus”  no problem! can load any sd xl lora

**Comment by Marscog** [comment] 2023-09-13 05:44
I was also getting this error on some generations. It seemed to be a not enough GPU memory error on some portrait orientations. I have a 3070 8GB card.  But not sure, I didn't investigate too much. I just went back to 1.0.64 and no problems.

**Comment by MoonRide303** [comment] 2023-09-13 05:54
@jasoncow007 @ping3839 Could you provide more details about CPU you're using? If you don't know exact model you can use something like [CPU-Z](https://www.cpuid.com/softwares/cpu-z.html) or [HWiNFO](https://www.hwinfo.com/).

@Marscog Seems to be separate issue, with that memory usage - if you'll be able to figure out reproducible scenario please describe it in separate issue, I will look into it.

**Comment by jasoncow007** [comment] 2023-09-13 06:51
@MoonRide303 yes,I used Fooocus's evn,  so that I could use two version of fooocus with one env,,,,what;s the difference between the original and MER env?

**Comment by MoonRide303** [comment] 2023-09-13 07:27
@jasoncow007 Mine uses a bit more up-to-date components - it was env produced by current Anaconda, with newer Python etc. I am not sure if this is the root problem here, just trying to get more details. I talked with comfy about it, and he suggested it might be CPU-specific thing.

**Comment by ping3839** [comment] 2023-09-13 10:00
> Again, still the same problems that would occur, (intel i5 11500, Gen11 CPU, Ram48GB, Vram 12G, RTX3060 12GB)
use env from the vanilla Fooocus or MRE env, It's going to be just as problematic.
H:\Fooocus_win64_2-0-0>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.0.0 MRE
Inference Engine exists.
Inference Engine checkout finished.
Total VRAM 12288 MB, total RAM 48841 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
adm 2816
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
Fooocus Expansion engine loaded.
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: sd_xl_refiner_1.0_0.9vae.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('product_shot_of-000002.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[Prompt Expansion] New suffix: intricate, highly detailed, centered, digital painting, artstation, concept art, smooth, sharp focus, illustration, artgerm, donato giancola, Joseph Christian Leyendecker, WLOP, Boris Vallejo, Artgerm Lau, Ruan Jia and Fenghua Zhong
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[Prompt Expansion] New suffix: extremely detailed, trending on artstation, in the style of makoto shinkai, raphael lacoste louis comfort tiffany, artgerm, karol bak, james jean, ross tran, 8 k hd, fine texture structure, 3 drender
loading new
loading new
loading in lowvram mode 256.0
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "H:\Fooocus_win64_2-0-0\Fooocus\modules\async_worker.py", line 373, in worker
    handler(task)
  File "H:\Fooocus_win64_2-0-0\Fooocus\modules\async_worker.py", line 207, in handler
    t['c'][1] = pipeline.clip_encode(sd=pipeline.xl_refiner, texts=t['positive'],
  File "H:\Fooocus_win64_2-0-0\Fooocus\modules\default_pipeline.py", line 224, in clip_encode
    cond, pooled = clip_encode_single(clip, text)
  File "H:\Fooocus_win64_2-0-0\Fooocus\modules\default_pipeline.py", line 202, in clip_encode_single
    result = clip.encode_from_tokens(tokens, return_pooled=True)
  File "H:\Fooocus_win64_2-0-0\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 120, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "H:\Fooocus_win64_2-0-0\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sdxl_clip.py", line 79, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "H:\Fooocus_win64_2-0-0\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd1_clip.py", line 18, in encode_token_weights
    out, pooled = self.encode(to_encode)
  File "H:\Fooocus_win64_2-0-0\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd1_clip.py", line 168, in encode
    return self(tokens)
  File "H:\Fooocus_win64_2-0-0\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "H:\Fooocus_win64_2-0-0\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd1_clip.py", line 149, in forward
    with precision_scope(model_management.get_autocast_device(device), torch.float32):
  File "H:\Fooocus_win64_2-0-0\python_embeded\lib\site-packages\torch\amp\autocast_mode.py", line 201, in __init__
    raise RuntimeError('User specified autocast device_type must be \'cuda\' or \'cpu\'')
RuntimeError: User specified autocast device_type must be 'cuda' or 'cpu'

**Comment by ping3839** [comment] 2023-09-13 10:08
I'll try running it again on another computer( note book) later today to see if the problem still occurs!

**Comment by Marscog** [comment] 2023-09-13 12:47
I just experimented and it is the LoRA issue, that is causing the "RuntimeError: User specified autocast device_type must be 'cuda' or 'cpu'" error.
I'm going to reinstall and see if that makes a difference. I've just been updating from the "run-mre.bat" file.

**Comment by MoonRide303** [comment] 2023-09-13 13:08
@ping3839 @Marscog You can also try restarting and updating to v2.0.3 - LoRAs should work fine, again. Lowering VRAM usage can also make comfy work better (not having to enter lowvram mode), so it might help with other issues as well.

**Comment by Marscog** [comment] 2023-09-13 13:18
Where can I find v2.0.3. I just updated and it still shows 2.0.0.

**Comment by Marscog** [comment] 2023-09-13 13:25
Nevermind, just updated again and got 2.0.3

**Comment by MoonRide303** [comment] 2023-09-13 13:43
@ping3839 @Marscog I also just pushed one more change (still v2.0.3), which should allow text encoder to stay on GPU - please check if it works now.

**Comment by ping3839** [comment] 2023-09-13 17:10
> @ping3839 @Marscog You can also try restarting and updating to v2.0.3 - LoRAs should work fine, again. Lowering VRAM usage can also make comfy work better (not having to enter lowvram mode), so it might help with other issues as well.

at v2.0.3, it's perfect working, Fooocus help me can be do more exquisite job, Thank you very much.

**Comment by MoonRide303** [comment] 2023-09-28 16:31
Problem seems solved - closing.

**Closed by MoonRide303** 2023-09-28 16:31 UTC
